### ISSUE TITLE
Javascript issues

### ISSUE THREAD

**Issue by Akhilknowsdawae** [imd1005-web-development-winter-2023/assignment-03-Akhilknowsdawae#2]
Inputted text is not getting added to the list and I can't figure out why.
Help would be very much appreciated.

**Comment by neilmispelaar** [comment]
https://github.com/imd1005-web-development-winter-2023/assignment-03-Akhilknowsdawae/blob/5464c81579d2bc5ccf61d486d033878beff3a6b8/main.js#L13

Start with the above line in your code. 

You are creating a variable with your To do list `ul` looking for a specific class name. 

Does an element with that specific class name exist in your page? 

Also, use the `console.log();` statements everywhere to trace where your program is and if you are experiencing any run time errors. 

You got this! 

Let me know if that helps.

**Comment by Akhilknowsdawae** [comment]
I've updated the javascript code but to no avail. I still can't figure out why the list is not getting updated.

**Comment by neilmispelaar** [comment]
Hey @Akhilknowsdawae 

Okay, as a first step, can you add a bunch of `console.log(“I am here at X (X being the function name)”, todos)` statements so that we can make sure your functions are running as expected and to see what the values inside the `todos` array are at different times in the app.

**Comment by Akhilknowsdawae** [comment]
I added a few console.log statements in the code and I also found this:
![image](https://user-images.githubusercontent.com/22270009/226081023-4b5dbd4c-7150-40ae-9d31-5054e36741eb.png)

**Comment by neilmispelaar** [comment]
That’s awesome! 

If you check out the error in red it says issue adding `addEventListener` on line 139. 

Line 139 you are adding an event listener to the form variable. Looks good. 

https://github.com/imd1005-web-development-winter-2023/assignment-03-Akhilknowsdawae/blob/9da4c41e12341e4e1e5b39144ab3d258ebd4251d/main.js#L139

And on line 15 you are initializing the variable by getting the item on the web page using the query selector and looking for a class “.” called 
“new-todo”. 

https://github.com/imd1005-web-development-winter-2023/assignment-03-Akhilknowsdawae/blob/9da4c41e12341e4e1e5b39144ab3d258ebd4251d/main.js#L15

However, when I look at your HTML code you don’t have an object with a class name of “new-todo”.

**Comment by neilmispelaar** [comment]
Remember: 

`.new-todo` finds an object with a class name of “new-todo”

`#new-todo` finds an object with an Id of “new-todo”

**Comment by Akhilknowsdawae** [comment]
Thank you so much for the help. I fixed the issue but ran into another one. 
I did a quick search online and it means that it is "trying to access a property of an object that is undefined"

![image_2023-03-17_235039414](https://user-images.githubusercontent.com/22270009/226083520-2052dd76-5b0a-43b4-a1ad-c1895bf806bd.png)

which is weird for me since I have a CreateElement:
![image](https://user-images.githubusercontent.com/22270009/226083760-2943f2f2-bd0b-40bd-87c9-87f1e789dfd6.png)
![image](https://user-images.githubusercontent.com/22270009/226083766-5dacb6f8-fff4-4577-9d2d-33e503d0a785.png)

**Comment by neilmispelaar** [comment]
On line 98, remember the error refers to the `todoList` object being “undefined”. 

How are you initializing and setting `todoList`? 

Double check the query selector for `todoList` is correct (the whole ID vs class name).

**Comment by Akhilknowsdawae** [comment]
Thank you again, I'm finally free from errors. But I'm now running into bugs and yet again Im completely clueless D:

https://user-images.githubusercontent.com/22270009/226084587-becd497f-980b-47d2-89e6-a029b864acd4.mp4

**Comment by Akhilknowsdawae** [comment]
It's creating the div element as well as the button to click on but the text, edit and delete buttons are not appearing when created and not to mention duplicates. That is everything I am able to decipher.

**Comment by neilmispelaar** [comment]
Hey @Akhilknowsdawae 

Phew! That’s a lot going on. Hang in there. We’ll get through this. 

If you need more time to sort this out it’s always available to you. 

For now: 

I would strongly recommend taking a step back, and just trying to do one small piece at a time. Right now you have a lot of code and a lot of different things going on. 

Let’s just start with writing a list item `li` when the form is submitted and use the text inside the input box. 

You already have the event handler for the form setup. And it’s already creating a list item. 

Step 1 
Comment out all of your extra code in the render function.

Just focus on creating an li and adding it to the list ul already on the page. (Just put dummy textContent in the li for now)

Step 2

When you are happy that your li being created on form submit event, the second step is to take the content from the input text box in the form and shove in into the li as text Content. 

There is an example in the class code repo for class 15 and some stuff in exercise 17/18 you can use. 

After that we can plot next steps. 

You got this!

**Comment by Akhilknowsdawae** [comment]
Hello @neilmispelaar, 
I did as you suggested and commented out everything and focus on creating the li... which isn't working D:
The inputted text is getting added to the array which is the only good sign so far. I looked into the exercises and class code repo for help but it isn't working .-.


![image](https://user-images.githubusercontent.com/22270009/226123397-21367a43-3419-43c3-a12d-29442375ead1.png)
![image](https://user-images.githubusercontent.com/22270009/226123380-0f27facf-c0bd-4061-90d7-e2ff52bae085.png)
![image](https://user-images.githubusercontent.com/22270009/226123382-7a6bdc51-71e1-4d4c-938f-d9f25676906b.png)

**Comment by neilmispelaar** [comment]
You're so close @Akhilknowsdawae !

Have a look at your `for` loop. You are correctly creating the list item, and correctly setting the class and correctly adding the text content. Woot woot. 

The only thing missing is that you aren't adding your `li` items to your `list`. So they are being created properly, but they aren't actually being added to the `list` on the page! That's why they aren't being displayed (if it isn't added to the page dom it won't ever be visible).

https://github.com/imd1005-web-development-winter-2023/assignment-03-Akhilknowsdawae/blob/871e6b09aab68d733bd9e7f6d391e30a47286f3a/main.js#L84-L88

You can add them to your `list` by doing the following in your for loop

```javascript

itemsList.appendChild(todoItem);

// Here's what the above line does
// itemsList is the todoList that is passed into the DisplayTodos function as the second function argument
// We use the appendChild method to add a child to our itemsList variable (the itemsList is our TodoList) 
// And lastly we pass in the todoItem that you created so that it's added to the itemsList

```

**Comment by Akhilknowsdawae** [comment]
It's finally working...! Kind of, I have a mix of questions and problems this time.

Edit: I managed to figure out the issue :D 


1. The code is accepting the input and prints it out exactly...?
![image](https://user-images.githubusercontent.com/22270009/226142214-e9d04b38-c2b6-47e2-ae8c-b1d9b5be65a8.png)
![image](https://user-images.githubusercontent.com/22270009/226142219-dc9dc49d-260a-4e11-b3c0-74ae3b7f14ab.png)
I'm pretty sure this is because of how I set up the const todo. If 'done' is true, the CSS will strike out the words. 
![image](https://user-images.githubusercontent.com/22270009/226142356-ccad18e7-e56b-4089-ba7c-a0820b7c4c5d.png)

Is there a way to only print 'content' in the input tag?
`<input type="text" value="Feed the cat" readonly>`



2. How would we target these elements to add classes etc?
![image](https://user-images.githubusercontent.com/22270009/226142429-1468da68-0ec0-402d-8f46-556d3baad135.png)
![image](https://user-images.githubusercontent.com/22270009/226142461-8954da07-24bd-4176-93ec-dd576abb27b1.png)

**Comment by neilmispelaar** [comment]
❤️ the progress! 

https://github.com/imd1005-web-development-winter-2023/assignment-03-Akhilknowsdawae/blob/26f4c95624da7f17fd097ca8c8f510eeeb51a20a/main.js#L77

Remember, in JavaScript variables, you can access properties of an object inside an array using the dot notation. 

```javascript

let array = [];

let firstTodo = { 
  text: "Hello world",
  done: false,
};

array.push(firstTodo); 

console.log(array[0].text); // Prints out "Hello world" (string) 
console.log(array[0].done); // Prints out false (not a string) 

// Also you don't need JSON stringify 
something.textContent = array[0].text;  // Text content now set to "Hello world"
```

**Comment by Akhilknowsdawae** [comment]
Hello @neilmispelaar! This is probably my last question, PROBABLY. 
I'm trying to add the class 'done' to todoItem once you click the input checkbox. This is what I've got so far in my code, which isn't working ._.

`var checkbox = (todoItem.input[type=checkbox]);
    checkbox.addEventListener("click", e=>{
      if(input.checked = true) {
        todoItem.classList.add("done");
      } else {
        todoItem.classList.remove("done");
      }
      console.log("hi i am here at DisplayTodos", todos);
      DisplayTodos();
    })`

**Comment by neilmispelaar** [comment]
I’ll have to look at this more in the morning but right away: 

`if(input.checked = true) {  `

First off the equal sign (one equal) isn’t a comparison operator, so this statement will always equal `true`. 

You need to use double or better yet triple equal operator. 

Also, what is the `input` object refer to?

**Comment by neilmispelaar** [comment]
If you aren’t already doing this, you will need to use a query selector or get element by id to get a reference to the input check mark inside the specific To Do list li

**Comment by Akhilknowsdawae** [comment]
> I’ll have to look at this more in the morning but right away:
> 
> `if(input.checked = true) { `
> 
> First off the equal sign (one equal) isn’t a comparison operator, so this statement will always equal `true`.
> 
> You need to use double or better yet triple equal operator.
> 
> Also, what is the `input` object refer to?

Thank you! I managed to get it to work!

**Comment by Akhilknowsdawae** [comment]
> > I’ll have to look at this more in the morning but right away:
> > `if(input.checked = true) { `
> > First off the equal sign (one equal) isn’t a comparison operator, so this statement will always equal `true`.
> > You need to use double or better yet triple equal operator.
> > Also, what is the `input` object refer to?
> 
> Thank you! I managed to get it to work!

Hello again! I managed to get it to work, but it only works for the first item on the list. 
I'm pretty sure it is because it is in the for loop but taking the event listener out of the for loop ruins the code.

also, this typeError keeps showing up
![image](https://user-images.githubusercontent.com/22270009/226210509-6fbe2b83-4bcc-47f1-a32e-fccee9857f76.png)

**Comment by Akhilknowsdawae** [comment]
Also is it possible if to extend the due date by a day or two? I have many assignments and a midterm coming up this term.

**Comment by neilmispelaar** [comment]
> also, this typeError keeps showing up 
> ![image](https://user-images.githubusercontent.com/22270009/226210509-6fbe2b83-4bcc-47f1-a32e-fccee9857f76.png)

Would recommend doing a `console.log(variable);` before line 57 to see what the value of the variable is and try to figure out why it's undefined, where `variable` is whatever is running on line 57 that is `undefined`.

It's likely you are references something incorrectly or a querySelector is returning null.

**Comment by neilmispelaar** [comment]
> Also is it possible if to extend the due date by a day or two? I have many assignments and a midterm coming up this term.

Your updated due date for Assignment 03 is now **March 26th at 11:59PM**.

I'm also going to be doing office hours this week for anyone that needs extra help on Assignment 03. 

Also be advised that Group Project work will ramp up this week so you should try to plan accordingly to balance both.
